# Generated by Django 3.2.9 on 2021-11-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klng', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='desc',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='link',
            new_name='github_link',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.RemoveField(
            model_name='users',
            name='githubLink',
        ),
        migrations.RemoveField(
            model_name='users',
            name='image',
        ),
        migrations.RemoveField(
            model_name='users',
            name='linkdinLink',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='linkedin_link',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='no project name', max_length=100)),
                ('desc', models.CharField(default='no description', max_length=400)),
                ('project_link', models.CharField(max_length=200, null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='klng.portfolio')),
            ],
        ),
    ]
