# Generated by Django 3.2.9 on 2021-11-05 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klng', '0002_auto_20211105_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='klng.users'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='about',
            field=models.CharField(default='No info about me', max_length=400),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='name',
            field=models.CharField(default='No name', max_length=100),
        ),
    ]
