# Generated by Django 3.2.9 on 2021-11-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klng', '0003_auto_20211105_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
