# Generated by Django 3.2.9 on 2021-11-09 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('klng', '0004_rename_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='user_name',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='klng.user'),
        ),
    ]
